### ISSUE TITLE
Ponder Django

### ISSUE THREAD

**Issue by Ghost-in-the-Chel** [A-Magenta-Monster/Lamia-Community#178]
Zephyr does this once a year, as a matter of routine and procedure.

**Comment by Zephyr-Crow** [comment]
Early on in the project, Flask made a lot of sense. Lamia was closed source, for fun, and no one had any clue what Lamia would look like in several years. I needed something lightweight, nimble, and fairly adaptable.

Thus, a micro framework made a lot of sense at that time. We're in a different place now. Lamia is open source, seeking traction, and in need of some form of long term stability and the ability to outlive my ability to be the solo developer.

A rewrite in Django would address some needs.

*The project would become more accessible to other developers* by providing stable conventions for project structure, and extensive documentation that would speak to those conventions. A Flask project has its own conventions and ways of doing things. A Django project, however, is a Django project. They do things in the Django way, which is generally documented or (where documentation fails) has some core developer that can speak to the methodology.

*The project would become more accessible to end users* by linking into the vast network of Django pluggables - https://djangopackages.org/categories/apps/ - everything on that site would suddenly become interoperable. Out of the box. That's insanely powerful!

Right now, how exactly would a project tie a store into Lamia? They'd have to do it clumsily. After a Django rewrite, it would be fucking simple. They'd just need to setup one of these - https://djangopackages.org/grids/g/ecommerce/ - and then install Lamia Community as well.

Django’s packages aren't always super plug and play. Most of them require customization and settings tweaks. Still, it would be a vastly improved ecosystem over what we have right now.

If we move over to Django, this would also give an opportunity to clean up some of the hacks and less appealing aspects of the current code base. Urls should be functional, multilingual support should have been considered from the beginning, templates shouldn't have been so monolithic. I can fix these issues and more during the rewrite. In addition to this, Django's standardized login and authentication modules would enable easier support for logging in via third party APIs.

Furthermore, if we're looking at adding developers as things currently are, then I would need to create developer documentation. This would be a daunting task currently. The way that Lamia does things is completely unique to Lamia. After Django, Lamia would be just another Django package, and there would be no need for Lamia-specific documentation. (Also… I could make tests. Alleviating a current anxiety that is plaguing me.)

There's also the current state of our dependencies. We are, unintentionally, building our own Django from a hodgepodge of various Python libraries and our own utilities. Only, unlike Django, our assortment is not centrally curated. It's a bit of a mess. Moving to Django would allow us to basically nuke all of these requirements entirely, and use the Django variants. I haven't analyzed it in depth, but at least twenty dependencies would vanish, probably more.

I think that there's a strong case to be made for this since a lot of the 1.00 issues could be closed during a rewrite. Our templates and Javascript would require minimal tweaks. I'll do an analysis later on.

**Comment by Ghost-in-the-Chel** [comment]
This would be lovely, if only for offering a good chance to rename 'categories' to boards, and 'topics' to threads, like sane sensible people. :T

**Comment by Zephyr-Crow** [comment]
Issues that would be made irrelevant by Django - meaning, they could be instantly closed:

#163 - there are existing Django apps for blogging that could provide blogs as a front page
#157 - Django has support for pluggable apps
#146 - We could simply make pluggables for Lamia features and let Django handle toggling
#144 - Django has pug support 
#135 - We would get this out of the box
#134 - We would get this for free as well 
#130 - This would be a freebie 
#125 - This would be a given
#124 - this would be a given
#115 - this would be completely configurable 
#114 - handled by Django 
#91 - Irrelevant due to rewriting blogs and making tests during that process
#83 - Irrelevant due to switching to a new or
#81 - Irrelevant due to using Django's functions for authentication
#66 - Included with refactoring
#63 - Resolved by refactoring
#6 - Resolved by migration to Django

The following issues could be completed during the rewrite:

Everything. 

After looking through our issues, not many things wouldn't be able to just be tied in during the rewrite.

**Comment by Zephyr-Crow** [comment]
Adding more -

We would get a few massive benefits to the rewrite.

Django-rest-framework and vue.js would simplify our templating code.

Django's permission system and an app or addon to dramatically simplify our permissions code.

Tests could be tied in from the beginning.

Multilingual support could be tied in as well.

There would be a massive time savings because I wouldn't need to write Lamia specific documentation. Pretty much everything would be Django standard.

Additional time savings would come from the fact that Django's admin environment is vastly better than what we're using atm, with less work.

We could tie in with a fancy admin environment skin and get an even sweeter experience - https://django-grappelli.readthedocs.io/en/latest/

**Comment by Zephyr-Crow** [comment]
It makes sense to me!

This is going to be a thing.

**Comment by Zephyr-Crow** [comment]
Simple truth is that Lamia grew up on Flask, got really really bigmchuge large and now would benefit from being built on django before it turns into a reimplementation of django, which is slowly becoming a thing as we add more and more features.

In my own estimates, using Django and a strong client side framework would futureproof us and trim the codebase by 2.5K lines of coffeescript, about 4K lines of HTML, and 4K or so lines of Python. The net effect of this would be to bring the total codebase down to about 15K lines of code, which would make the framework extremely maintainable.

![screenshot 2018-06-04 21 16 49](https://user-images.githubusercontent.com/36945622/40955074-a360683c-683c-11e8-814b-2ee9c2dc892a.png)

I look forward to these numbers going down a bit, in addition to Lamia gaining a place in the ecosystem of apps that exists in django, which would make it much more approachable and easier to tie into existing Python projects.
